name: GitHub - Stats - Readme

on:
  workflow_dispatch:
  schedule:    
    - cron: "0 */2 * * *"

jobs:
  update-readme:
    name: GitHub - Stats - Readme
    runs-on: ubuntu-latest
    steps:
      - uses: athul/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
