name: GitHub - WakaTime - Readme
on:
  push:
    branches: [ master ]
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:
jobs:
  update-readme:
    name: Update the WakaTime Stat
    runs-on: ubuntu-latest
    steps:
      - uses: avinal/Profile-Readme-WakaTime@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GITHUB_TOKEN: ${{ github.token }}
