name: GitHub - Activity - Readme

on:
  workflow_dispatch:
  schedule:    
    - cron: "0 */1 * * *"
  workflow_dispatch:

jobs:
  update-readme:
    name: GitHub - Activity - Readme
    runs-on: ubuntu-latest
    steps:
      - uses: athul/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
